### ISSUE TITLE
missing games in clean-cpc-db v1.2

### ISSUE THREAD

**Issue by aderumier** [libretro/libretro-cap32#147]
Hi, I have found missing commercial games in cleandb 1.2  (not present in have or miss txt)

Yie Ar Kung-Fu https://www.cpc-power.com/index.php?page=detail&num=1425
Ninja Spirit https://www.cpc-power.com/index.php?page=detail&num=114
Sauvez Yurk https://www.cpc-power.com/index.php?page=detail&num=1879
aigle d'or le retour https://www.cpc-power.com/index.php?page=detail&num=89
builderland https://www.cpc-power.com/index.php?page=detail&num=493
locomotion https://www.cpc-power.com/index.php?page=detail&num=1310

**Comment by DSkywalk** [comment]
Thanks for your report and sorry for the delay, for cleandb you can also use [our dat repo](https://github.com/clean-cpc-db/dat/issues/new)

Your report:
* Yie Ar Kung-Fu: The name in dat **is incorrect** but the dump/crc is [here](https://github.com/libretro/libretro-cap32/blob/master/libretro/db/db-clean.h#L3169) and [here](https://github.com/clean-cpc-db/dat/blob/main/clean-cpc-db.dat#L15232) :warning: 
* Ninja Spirit: Missing (_v2_ CRC 80BB73F4)
* Sauvez Yurk: Missing (375D3A28, 30F33E46)
* Aigle d'or le retour / Golden Eagle: Missing (5CA0FD3C, B91DC1A9, 5256B156, 44998F95) and need a loader/fix :warning: 
* Builderland: Missing (_fix_ CRC 0CBFD92F)
* Locomotion: There isn't a good dump, but the crack seems clean for me :+1: (CRC 21740220)

Really thanks for your report again @aderumier :+1:

**Comment by DSkywalk** [comment]
fixed after 87324412065dec08c5a4f290d966772ed14560fe
new clean-cpc-db released: https://github.com/clean-cpc-db/dat/commits/main/

enjoy! :sparkles:

**Comment by aderumier** [comment]
Many thanks !  perfect time, I was working on my collection for x-mas, I think they are still missing some games, I'll check the 1.3 and compare :)

Thanks for you hard work !
